"""empty message

Revision ID: 89dc0da3122e
Revises: a5038376088c
Create Date: 2019-08-25 07:06:24.809655

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89dc0da3122e'
down_revision = 'a5038376088c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('url_foto', sa.String(length=200), nullable=True))
    op.add_column('product', sa.Column('url_foto', sa.String(length=200), nullable=True))
    op.add_column('sellers', sa.Column('url_foto', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sellers', 'url_foto')
    op.drop_column('product', 'url_foto')
    op.drop_column('customers', 'url_foto')
    # ### end Alembic commands ###
