"""empty message

Revision ID: f4d57b25e28f
Revises: 
Create Date: 2019-08-19 12:11:38.796999

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4d57b25e28f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orderdetails', sa.Column('order_id', sa.Integer(), nullable=True))
    op.add_column('orderdetails', sa.Column('product_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'orderdetails', 'orders', ['order_id'], ['id'])
    op.create_foreign_key(None, 'orderdetails', 'product', ['product_id'], ['id'])
    op.add_column('product', sa.Column('category_id', sa.Integer(), nullable=False))
    op.add_column('product', sa.Column('seller_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'product', 'sellers', ['seller_id'], ['id'])
    op.create_foreign_key(None, 'product', 'category', ['category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'product', type_='foreignkey')
    op.drop_constraint(None, 'product', type_='foreignkey')
    op.drop_column('product', 'seller_id')
    op.drop_column('product', 'category_id')
    op.drop_constraint(None, 'orderdetails', type_='foreignkey')
    op.drop_constraint(None, 'orderdetails', type_='foreignkey')
    op.drop_column('orderdetails', 'product_id')
    op.drop_column('orderdetails', 'order_id')
    # ### end Alembic commands ###
